Repository theforeman/puppet-puppet, pull requests merged in 2018-11, with the labels that each got.

#648 Refactor puppetserver spec testing
  spec/classes/puppet_server_puppetserver_spec.rb
Labels: Needs testing, Not yet reviewed

#651 adjust puppetversion to puppetserver_version mapping
  manifests/params.pp
Labels: Bug, Needs testing

#647 Add support for managing jetty threads
  manifests/init.pp
  manifests/server.pp
  manifests/server/puppetserver.pp
  spec/classes/puppet_server_puppetserver_spec.rb
  templates/server/puppetserver/conf.d/webserver.conf.erb
Labels: Enhancement, Needs testing

#643 Update CA related files for Puppetserver 5.3.6
  manifests/init.pp
  manifests/params.pp
  manifests/server.pp
  manifests/server/puppetserver.pp
  spec/classes/puppet_server_puppetserver_spec.rb
  templates/server/puppetserver/conf.d/auth.conf.erb
  templates/server/puppetserver/conf.d/ca.conf.erb
Labels: Needs testing

#642 Add Puppet 6 support
  .fixtures.yml
  .sync.yml
  .travis.yml
  manifests/params.pp
  manifests/server/config.pp
  spec/acceptance/puppetserver_upgrade_2_6_0_to_2_7_2_spec.rb
  spec/classes/puppet_server_spec.rb
Labels: Enhancement, Needs testing, Not yet reviewed

#655 Mark as compatible with Puppet 6
  metadata.json
Labels: Needs testing, Not yet reviewed
