Repository theforeman/puppet-puppet, pull requests merged in 2018-10, with the labels that each got.

#631 Add shared gem path for Puppetserver >= 5.3
  manifests/server/puppetserver.pp
  spec/classes/puppet_server_puppetserver_spec.rb
  templates/server/puppetserver/conf.d/puppetserver.conf.erb
Labels: Bug, Needs testing

#619 updated auth.conf for the "puppet facts upload" command (puppetserver 5.5)
  manifests/params.pp
  spec/classes/puppet_server_puppetserver_spec.rb
  templates/server/puppetserver/conf.d/auth.conf.erb
Labels: Needs testing

#640 Test for the correct line endings on Windows
  spec/classes/puppet_config_spec.rb
  spec/defines/puppet_config_entry_spec.rb
Labels: Needs testing, Not yet reviewed

#638 reduce diff to Puppet distributed files
  spec/classes/puppet_server_puppetserver_spec.rb
  templates/auth.conf.erb
  templates/server/puppetserver/conf.d/auth.conf.erb
  templates/server/puppetserver/conf.d/metrics.conf.erb
  templates/server/puppetserver/conf.d/puppetserver.conf.erb
Labels: Needs testing, Not yet reviewed

#644 Update README
  README.md
Labels: Needs testing, Not yet reviewed
