Repository theforeman/puppet-puppet, pull requests merged in 2018-07, with the labels that each got.

#605 Support Ubuntu/bionic, drop Debian 7 & Fedora 25
  .travis.yml
  manifests/params.pp
  metadata.json
  spec/classes/puppet_agent_service_spec.rb
  spec/classes/puppet_agent_service_systemd_spec.rb
Labels: Needs testing

#606 msync: Acceptance tests update
  .sync.yml
  .travis.yml
  Gemfile
  spec/acceptance/nodesets/docker/centos-6.yml
  spec/acceptance/nodesets/docker/centos-7.yml
  spec/acceptance/nodesets/docker/debian-8.yml
  spec/acceptance/nodesets/docker/debian-9.yml
  spec/acceptance/nodesets/docker/ubuntu-14.04.yml
  spec/acceptance/nodesets/docker/ubuntu-16.04.yml
Labels: Modulesync, Needs testing, Not yet reviewed

#607 msync: rake changelog & beaker hostname
  Gemfile
  Rakefile
Labels: Needs testing, Not yet reviewed

#608 Release 9.1.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing
