Repository theforeman/puppet-puppet, pull requests merged in 2018-04, with the labels that each got.

#588 Remove unused _template options
  README.md
  manifests/config.pp
  manifests/init.pp
  manifests/params.pp
Labels: Backwards incompatible, Needs testing, Not yet reviewed

#589 Move some settings into an advanced section
  manifests/init.pp
Labels: Needs testing, Not yet reviewed

#585 WIP: Add systemd_randomizeddelaysec
  manifests/agent/service/systemd.pp
  manifests/init.pp
  manifests/params.pp
  spec/classes/puppet_agent_service_systemd_spec.rb
  templates/agent/systemd.puppet-run.timer.erb
Labels: Needs testing

#590 adding support for Amazon Linux
  manifests/params.pp
Labels: Needs testing
