Repository theforeman/puppet-puppet, pull requests merged in 2018-12, with the labels that each got.

#657 Revert "Test for the correct line endings on Windows"
  spec/classes/puppet_config_spec.rb
  spec/defines/puppet_config_entry_spec.rb
Labels: Needs testing, Not yet reviewed

#656 Release 10.1.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, Not yet reviewed

#650 Remove passenger support
  README.md
  manifests/init.pp
  manifests/params.pp
  manifests/server.pp
  manifests/server/config.pp
  manifests/server/install.pp
  manifests/server/passenger.pp
  manifests/server/puppetserver.pp
  manifests/server/rack.pp
  manifests/server/service.pp
  spec/classes/puppet_server_passenger_spec.rb
  spec/classes/puppet_server_puppetserver_spec.rb
  spec/classes/puppet_server_service_spec.rb
  templates/server/config.ru.erb
Labels: Backwards incompatible, Needs testing

#639 namespace extlib functions
  manifests/agent/service/cron.pp
  manifests/agent/service/systemd.pp
  metadata.json
Labels: Enhancement, Needs testing

#653 Remove dynamic and config environments
  README.md
  manifests/init.pp
  manifests/params.pp
  manifests/server.pp
  manifests/server/config.pp
  manifests/server/env.pp
  spec/classes/puppet_server_spec.rb
  spec/defines/puppet_server_env_spec.rb
Labels: Backwards incompatible, Needs testing

#649 Drop support for puppetserver < 2.7
  manifests/server/puppetserver.pp
  spec/acceptance/puppetserver_upgrade_2_6_0_to_2_7_2_spec.rb
  spec/classes/puppet_server_puppetserver_spec.rb
  templates/server/puppetserver/conf.d/puppetserver.conf.erb
Labels: Backwards incompatible, Needs testing, Not yet reviewed

#660 Install JDK 8 on Debian/jessie for Puppetserver 5+
  .travis.yml
  spec/acceptance/puppetserver_latest_spec.rb
  spec/acceptance/puppetserver_upgrade_2_6_0_to_2_7_2_spec.rb
Labels: Needs testing

#661 remove apache dependency and leftovers
  .fixtures.yml
  manifests/init.pp
  manifests/params.pp
  manifests/server.pp
  metadata.json
Labels: Backwards incompatible, Needs testing

#665 Remove $deb_naio_package & puppet-common install
  manifests/params.pp
Labels: Enhancement, Needs testing, Not yet reviewed
