Repository theforeman/puppet-puppet, pull requests merged in 2019-01, with the labels that each got.

#666 Use Bundler 1.17.3 on Ruby 2.1.9
  .travis.yml
Labels: Needs testing, Not yet reviewed

#663 Set more data types and document classes & defines
  manifests/agent.pp
  manifests/agent/config.pp
  manifests/agent/install.pp
  manifests/agent/service.pp
  manifests/agent/service/cron.pp
  manifests/agent/service/daemon.pp
  manifests/agent/service/systemd.pp
  manifests/config.pp
  manifests/config/agent.pp
  manifests/config/entry.pp
  manifests/config/main.pp
  manifests/config/master.pp
  manifests/params.pp
  manifests/server.pp
  manifests/server/config.pp
  manifests/server/enc.pp
  manifests/server/install.pp
  manifests/server/puppetserver.pp
  manifests/server/service.pp
Labels: Needs testing, Not yet reviewed

#667 add Puppetserver 5.x upgrade test
  spec/acceptance/puppetserver_upgrade_5_1_3_to_5_3_6_spec.rb
Labels: Needs testing

#659 Add unmanaged Puppet Agent runmode
  manifests/agent/service.pp
  manifests/agent/service/cron.pp
  manifests/agent/service/daemon.pp
  manifests/agent/service/systemd.pp
  manifests/init.pp
  spec/classes/puppet_agent_spec.rb
Labels: Enhancement, Needs testing

#669 Release 11.0.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing
