Repository theforeman/puppet-puppet, pull requests merged in 2019-11, with the labels that each got.

#712 Restart Puppet Agent service after updating the package
  manifests/agent.pp
Labels: Bug, Needs testing

#713 Update GHCG gem and drop rdoc
  Gemfile
Labels: Needs testing, Not yet reviewed, skip-changelog

#715 Stop acceptance tests on EL7
  .sync.yml
  .travis.yml
Labels: Needs testing, Not yet reviewed
