Repository theforeman/puppet-puppet, pull requests merged in 2019-03, with the labels that each got.

#682 Fixes #26199 - Fix dependency cycle when using git_repo
  manifests/server/config.pp
  manifests/server/install.pp
  spec/classes/puppet_server_spec.rb
Labels: Bug, Needs testing, Not yet reviewed

#683 Handle the pluginsync setting deprecation
  manifests/agent/config.pp
Labels: Enhancement, Needs testing

#684 drop EOL OSes
  manifests/params.pp
  metadata.json
  spec/spec_helper.rb
Labels: Needs testing

#686 add 2018 to osreleasemajor for agent_restart_command
  manifests/params.pp
Labels: Needs testing, Not yet reviewed

#688 remove Debian 8 support
  .travis.yml
  metadata.json
  spec/acceptance/puppetserver_config_spec.rb
  spec/acceptance/puppetserver_latest_spec.rb
Labels: Backwards incompatible, Needs testing

#690 Configurable minute and hour for cronjob and systemd.timer
  manifests/agent/service.pp
  manifests/agent/service/cron.pp
  manifests/agent/service/systemd.pp
  manifests/init.pp
  spec/classes/puppet_agent_spec.rb
  templates/agent/systemd.puppet-run.timer.erb
Labels: Needs testing, Not yet reviewed
