Repository theforeman/puppet-puppet, pull requests merged in 2019-04, with the labels that each got.

#685 drop Puppet 4
  .sync.yml
  .travis.yml
  Gemfile
  README.md
  manifests/params.pp
  manifests/server.pp
  manifests/server/puppetserver.pp
  metadata.json
  spec/acceptance/puppetserver_config_spec.rb
  spec/acceptance/puppetserver_latest_spec.rb
  spec/acceptance/puppetserver_upgrade_2_6_0_to_2_7_2_spec.rb
  spec/acceptance/puppetserver_upgrade_5_3_6_to_5_3_7_spec.rb
  spec/classes/puppet_server_puppetserver_spec.rb
  templates/auth.conf.erb
  templates/server/puppetserver/conf.d/auth.conf.erb
  templates/server/puppetserver/conf.d/puppetserver.conf.erb
  templates/server/puppetserver/services.d/ca.cfg.erb
Labels: Backwards incompatible, Needs testing

#689 add Puppetserver 6.3 auth.conf update
  spec/classes/puppet_server_puppetserver_spec.rb
  templates/server/puppetserver/conf.d/auth.conf.erb
Labels: Needs testing

#693 Use current timeout management variables
  manifests/agent/config.pp
  manifests/init.pp
  manifests/params.pp
  spec/classes/puppet_server_spec.rb
Labels: Backwards incompatible, Needs testing

#692 Release 12.0.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs re-review, Needs testing
