Repository theforeman/puppet-puppet, pull requests merged in 2020-05, with the labels that each got.

#737 Switch AIO detection to use aio_agent_version fact
  manifests/params.pp
  spec/support/aio.rb
Labels: Enhancement, Needs testing

#739 Drop EOL Windows 7, 2008 R2
  metadata.json
Labels: Needs testing

#732 Refactor PuppetDB integration
  README.md
  manifests/init.pp
  manifests/params.pp
  manifests/server.pp
  manifests/server/config.pp
  manifests/server/puppetdb.pp
  spec/classes/puppet_server_puppetdb_spec.rb
  spec/classes/puppet_server_spec.rb
Labels: Backwards incompatible, Needs re-review, Needs testing

#740 Modulesync: Require voxpupuli-test 1.4
  Gemfile
Labels: Needs testing, Not yet reviewed

#741 Revert "Convert the systemd timer service to camptocamp/systemd"
  manifests/agent/service/systemd.pp
  spec/classes/puppet_agent_spec.rb
Labels: Needs testing

#742 Fixes #29735 - support el8
  metadata.json
  spec/classes/puppet_agent_spec.rb
Labels: Needs testing

#745 Add Fedora 31, drop Fedora 26
  .sync.yml
  .travis.yml
  metadata.json
  spec/acceptance/puppet_spec.rb
  spec/acceptance/puppetserver_config_spec.rb
  spec/acceptance/puppetserver_latest_spec.rb
  spec/acceptance/puppetserver_upgrade_5_3_6_to_5_3_7_spec.rb
  spec/acceptance/puppetserver_upgrade_6_7_0_to_6_7_2_spec.rb
  spec/setup_acceptance_node.pp
  spec/support/acceptance/puppetserver.rb
Labels: Needs testing, Not yet reviewed

#746 Support Ubuntu Focal (20.04)
  .sync.yml
  .travis.yml
  metadata.json
  spec/classes/puppet_agent_spec.rb
  spec/support/acceptance/puppetserver.rb
Labels: Enhancement, Needs testing

#744 Release 14.0.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog

#747 Don't re-create existing CA certs
  manifests/server/config.pp
  spec/classes/puppet_server_spec.rb
Labels: Bug, Needs testing
