Repository theforeman/puppet-puppet, pull requests merged in 2020-04, with the labels that each got.

#733 Allow extlib 5.x
  metadata.json
Labels: Needs testing

#729 add Ubuntu integration tests
  .sync.yml
  .travis.yml
  spec/spec_helper_acceptance.rb
Labels: Needs testing, Not yet reviewed

#731 Add server_trusted_external_command parameter
  manifests/init.pp
  manifests/params.pp
  manifests/server.pp
  manifests/server/config.pp
  spec/classes/puppet_server_spec.rb
Labels: Needs testing

#710 Convert the systemd timer service to camptocamp/systemd
  README.md
  manifests/agent/service/systemd.pp
  metadata.json
  spec/classes/puppet_agent_spec.rb
  spec/spec_helper_acceptance.rb
Labels: Needs testing, Not yet reviewed

#736 Drop Foreman API version parameters
  manifests/init.pp
  manifests/params.pp
  manifests/server.pp
  manifests/server/config.pp
Labels: Backwards incompatible, Needs testing
