Repository theforeman/puppet-puppet, pull requests merged in 2023-05, with the labels that each got.

#869 Stop managing services.d dir in /opt/puppetlabs
  manifests/server/puppetserver.pp
  spec/classes/puppet_server_puppetserver_spec.rb
Labels: Not yet reviewed, Enhancement

#871 Mark compatible with puppetlabs/concat 8.x
  metadata.json
Labels: Not yet reviewed

#843 Keep ruby's system Gem.dir in gem-path on FreeBSD
  manifests/server/puppetserver.pp
  spec/classes/puppet_server_puppetserver_spec.rb
Labels: Needs testing, Bug

#873 Drop Puppet 6 support
  .fixtures.yml
  README.md
  manifests/config.pp
  manifests/init.pp
  manifests/params.pp
  manifests/server.pp
  manifests/server/config.pp
  manifests/server/puppetserver.pp
  metadata.json
  spec/acceptance/puppetserver_upgrade_spec.rb
  spec/classes/puppet_config_spec.rb
  spec/classes/puppet_server_puppetserver_spec.rb
  spec/classes/puppet_server_spec.rb
  spec/support/acceptance/puppetserver.rb
  templates/auth.conf.erb
  templates/server/puppetserver/conf.d/auth.conf.erb
  templates/server/puppetserver/conf.d/puppetserver.conf.erb
Labels: Backwards incompatible

#874 Respect puppet::server::additional_settings parameter
  manifests/server/config.pp
Labels: Not yet reviewed, Bug

#876 Release 17.0.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog
