Repository theforeman/puppet-puppet, pull requests merged in 2023-11, with the labels that each got.

#889 Drop Debian 10 & Ubuntu 18.04
  metadata.json
Labels: Backwards incompatible

#890 Test puppetserver on Debian 11
  spec/acceptance/puppetserver_upgrade_spec.rb
  spec/support/acceptance/puppetserver.rb
Labels: Enhancement

#893 Fix CentOS 9 support in metadata.json
  metadata.json
  spec/acceptance/puppetserver_upgrade_spec.rb
Labels: Bug

#896 Add Debian 12 support
  metadata.json
  spec/support/acceptance/puppetserver.rb
Labels: Enhancement

#892 set PrivateTmp=true for puppetserver
  manifests/server/puppetserver.pp
Labels: Enhancement

#895 Add Ubuntu 22.04 support
  metadata.json
  spec/acceptance/puppetserver_upgrade_spec.rb
  spec/support/acceptance/puppetserver.rb
Labels: Enhancement

#899 Release 19.0.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog

#900 Add support for OracleLinux/AlmaLinux/Rocky 9
  metadata.json
  spec/classes/puppet_agent_spec.rb
Labels: Enhancement
